### ISSUE TITLE
Issue with Icingaweb 2 Graphite plugin

### ISSUE THREAD

**Issue by tbaror** [philiphoy/icingaweb2-module-graphite#6]
I added graphite plugin to Icinga web2 and enable it ,but now when i am trying to visualize graphs i get following page error attached image
Any idea?
Please advice
Thanks 
![grap_icinga](https://cloud.githubusercontent.com/assets/217691/7612873/1aa08fe4-f996-11e4-8a6a-79ada3a03a42.png)

**Comment by philiphoy** [comment]
That is just an iframe and what you see there is http://www.graphite.com. You need to configure the plugin to use your own graphite url. See /etc/icingaweb/modules/graphite/config.in and change base_url.

**Comment by tbaror** [comment]
Thanks for the answer ,  I manually created config.ini with following 
[graphite]
metric_prefix = icinga
base_url = /render?
since my graphite is installed local , now its shows the graph nicely but when i choose for example last 10min 1hr and so forth i get following gibberish screen attached (looks likes png that that not render well) ,
any idea ?
Thanks
![5-16-2015 9-07-41 pm](https://cloud.githubusercontent.com/assets/217691/7667440/4e288b42-fc10-11e4-9d75-4530939f243a.png)

**Comment by philiphoy** [comment]
What is the source (src) for the iframe?

**Comment by tbaror** [comment]
Hi ,
I don't see the iframe , i just see that when i click on time frame 

10 minutes  1 hour  12 hours    1 day   1 week  1 month     1 year
i get the i mage in a div instead of img , but when i right click and Open link in new TAB  i get img time frame correctly
![fullgraph](https://cloud.githubusercontent.com/assets/217691/7676413/e6370468-fd4b-11e4-9362-9091c7983c25.png)
![divpng](https://cloud.githubusercontent.com/assets/217691/7676417/eb781e44-fd4b-11e4-955b-ed8f4b2c3bd9.png)

![rightclick](https://cloud.githubusercontent.com/assets/217691/7676419/f0515ebc-fd4b-11e4-887e-256a34f5844e.png)

**Comment by mipapo** [comment]
Same problem here.
I have to servers with Icinga2, Icingaweb2 + Graphite
On the first server:
Ubuntu 14.04.2 LTS (GNU/Linux 2.6.32-37-pve x86_64)
Graphite is running on an extra subdomain.

Second server:
Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-38-generic x86_64)
Graphite and Icingaweb running on the same domain.

**Comment by kain64** [comment]
as a "dirty" hf replace:  /usr/share/icingaweb2/modules/graphite/application/views/scripts/index/index.phtml
with:
<div class="controls">
    <?= $tabs->showOnlyCloseButton() ?>
</div>
<div class="content">
  <table class="avp" style="width: 800px; text-align: center;">
    <tr>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-10min">10 minutes</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-1h">1 hour</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-12h" active>12 hours</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-1d">1 day</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-1w">1 week</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-1mon">1 month</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-1y">1 year</a></td>
    </tr>
  </table>
  <iframe name ="graph_iframe" src="<?= "http://" . $_SERVER['SERVER_ADDR'] . urldecode($this->url) ?>&from=-1d" style="height: 700px; width: 800px" frameborder="no"></iframe>
</div>

**Comment by kain64** [comment]
need to replace replace relative path to absolute like here: https://github.com/kain64/icingaweb2-module-graphite/commit/5a8125200aabf8f111c7bf7ad3657540253d9d5d. 
/usr/share/icingaweb2/modules/graphite/application/views/scripts/index/index.phtml
it's work for me. but I'm nube in PHP : )

**Comment by philiphoy** [comment]
Thanks for taking a look @kain64 however the path is absolute already. Also thanks for introducing me to the term "nub", i intend to take that as my own..

**Comment by philiphoy** [comment]
Duh looking at it again thanks to @kain64 's insight i think i see the problem now. @tbaror and @mipapo please use an absolute url for the configuration setting "base_url" and see if that helps.

**Comment by arsenip** [comment]
I came across both issues found here after fixing the 'No Data' issue by updating Grapher.php per https://github.com/findmypast/icingaweb2-module-graphite/issues/23

the first was fixed by adding a config.ini in /etc/icingaweb2/modules/graphite (note this not the /usr/share/icingaweb2/modules path) and ensuring the base_url was a full path (http://yourhost.yourdomain.com/render?). Mine is something like: 

[graphite]
metric_prefix = icinga
base_url = http://graphite.host.domain.com/render?
legacy_mode = true
service_name_template = "$host.name$.$service.name$"
host_name_template = "$host.name$"
graphite_args_template = "&target=$target$&source=0&width=300&height=120&hideAxes=true&lineWidth=2&hideLegend=true&colorList=049BAF"
graphite_large_args_template = "&target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=800&height=700&colorList=049BAF&lineMode=connected"

the second issue - large graph png being incorrectly rendered as gibberish - i fixed by making sure both my icingaweb2 and graphite instances were configured as vhosts (i have them running on the same phyiscal machine), as the issue appeared when icingaweb2 was not running as a vhost using the default icingaweb2 config. Equally you then need to update your icingaweb2-module-graphite's config.ini so the base_url points to the vhost address (like my example above)

hope this helps someone.

**Comment by MaRoMa1** [comment]
@tbaror I have your same problem: I added graphite plugin to Icinga web2 and enable it ,but now when i am trying to visualize graphs i get following page error attached image.
Can you help me what is the solution
Thank you a lot
